@startuml

class Inputs
class Outputs
class Files
class Program
class Interactive
class Graphical
class NonGranpical
class NonInteractive
class Machine
class User 
class JobSubmission

User -- Machine : Logged In

Machine "1" -- "*" Program : runs


Workflow "0..1" -- "1..*" JobSubmission : holds

JobSubmission "1" -- "1" Program : uses
JobSubmission "1" -- "1.*" Outputs : creates 
JobSubmission "1" -- "*" Inputs : ingests

Program <|-- Interactive
Program <|-- NonInteractive

Interactive <|-- Graphical
Interactive <|-- NonGranpical

Inputs "1" -- "1..*" Files
Outputs "1" --  "1..*" Files

@enduml

